platform :ios, '8.0'

target 'AKGPUImage' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'ResponsiveLabel', '~> 1.0.10'
  pod 'TMCache', '~> 2.1.0'
  pod 'CRToast', '~> 0.0.9'
  pod 'JSONModel', '~> 1.2.0'
  pod 'YUGPUImageHighPassSkinSmoothing', '~> 1.2'
  pod 'GPUImage', '~> 0.1.7'
  pod 'JTObjectMapping', '~> 1.1.2'
  pod 'Aspects', '~> 1.4.1'
  pod 'CocoaLumberjack'
end
